In [1]:

import numpy as np


def accuracy(y_true, y_pred):
    correct = 0
    for i in range(len(y_true)):
        if y_true[i] == y_pred[i]:
            correct += 1
    return correct / len(y_true) * 100

In [2]:
y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1])

print(accuracy(y_true, y_pred))

83.33333333333334


In [3]:
def entropy(labels, base=None):
    from math import log, e
    n_labels = len(labels)

    if n_labels <= 1:
        return 0

    value, counts = np.unique(labels, return_counts=True)
    probs = counts / n_labels
    n_classes = np.count_nonzero(probs)

    if n_classes <= 1:
        return 0

    ent = 0.

    base = e if base is None else base
    for i in probs:
        ent -= i * log(i, base)
    return ent


labels = [1,3,5,2,3,5,3,2,1,3,4,5]
entropy(labels)

1.5171063970610277

In [7]:
def entropy(labels, base=None):
  from math import log, e
  value, counts = np.unique(labels, return_counts=True)
  probs = counts/len(labels)
  ent = 0.
  print(value,probs)
  for i in probs:
    ent -= i*log(i)
  return ent


labels = [1,3,5,2,3,5,3,2,1,3,4,5]
entropy(labels)

[1 2 3 4 5] [0.16666667 0.16666667 0.33333333 0.08333333 0.25      ]


1.5171063970610277

In [8]:
def binary_crossentropy(y_true, y_pred):
    y_pred = np.clip(y_pred, 0.0000001, 1-0.0000001)
    return -y_true * np.log(y_pred) - (1-y_true) * np.log(1-y_pred)

In [13]:
y_true = np.array([1, 0, 1, 1, 0, 1, 0])
y_pred = np.array([0, 0, 1, 1, 0, 1, 1])

binary_crossentropy(y_true, y_pred).round(2)

array([16.12,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 16.12])

In [11]:
def categorical_crossentropy(y_true, y_pred):
    # przyciecie wyniku tak aby nie dzielic przez 0
    y_pred = np.clip(y_pred, 0.0000001, 1-0.0000001)
    return -np.sum(y_true * np.log(y_pred), axis=-1)

In [14]:
y_true = np.array([1, 0, 0, 0, 0])
y_pred = np.array([0.4, 0.3, 0.05, 0.05, 0.2])

categorical_crossentropy(y_true, y_pred)


0.916290731874155

In [15]:
y_true = np.array([1, 0, 0, 0, 0])
y_pred = np.array([0.98, 0.01, 0.0, 0.0, 0.01])

categorical_crossentropy(y_true, y_pred)

0.020202707317519466

In [16]:
y_true = np.array([[1, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0],
                  [1, 0, 0, 0, 0]])
y_pred = np.array([[0.4, 0.3, 0.05, 0.05, 0.2],
                  [0.05, 0.2, 0.0, 0.7, 0.05],
                  [0.98, 0.01, 0.0, 0.0, 0.01]])

categorical_crossentropy(y_true, y_pred)

array([0.91629073, 0.35667494, 0.02020271])